In [2]:
#Agilan Ampigaipathar
#100553054

#Imports
import numpy as np
import random as rnd

#Define function
def WhiteWash():
    m = 15
    a = []
    b = []
    c = []
    
    #For loop to append to arrays with random numbers between 0 and 1 
    for i in range (0,m):
        
        a.append(rnd.uniform(0,1))
        b.append(rnd.uniform(0,1))
        c.append(rnd.uniform(0,1))
    
    abc = np.asarray((a,b,c))
    array = np.transpose(abc)
    
    print (array, '\n')
    
    for i in range (0,10):
        
        #Average with the color white
        array[:][:][i] = ((array[:][:][i]+1)/2)
        
    return array

new_array = WhiteWash ()
print (new_array)

[[ 0.20886598  0.68255824  0.24479562]
 [ 0.45657072  0.03085639  0.43040942]
 [ 0.14559556  0.85288651  0.72061577]
 [ 0.77781635  0.58536206  0.85823104]
 [ 0.27363501  0.88355231  0.69708513]
 [ 0.52596227  0.8593041   0.38397798]
 [ 0.24241862  0.54819041  0.00184846]
 [ 0.69820244  0.0092162   0.87743506]
 [ 0.2834071   0.22327643  0.89677424]
 [ 0.66617793  0.9329709   0.83139839]
 [ 0.44498006  0.02884533  0.6359004 ]
 [ 0.86317358  0.45738308  0.28023643]
 [ 0.03615782  0.52541535  0.84708522]
 [ 0.32041542  0.724952    0.6869494 ]
 [ 0.96809792  0.31425109  0.93560751]] 

[[ 0.60443299  0.84127912  0.62239781]
 [ 0.72828536  0.5154282   0.71520471]
 [ 0.57279778  0.92644325  0.86030789]
 [ 0.88890817  0.79268103  0.92911552]
 [ 0.63681751  0.94177616  0.84854256]
 [ 0.76298113  0.92965205  0.69198899]
 [ 0.62120931  0.77409521  0.50092423]
 [ 0.84910122  0.5046081   0.93871753]
 [ 0.64170355  0.61163822  0.94838712]
 [ 0.83308897  0.96648545  0.91569919]
 [ 0.44498006  0.02884